// Run with NODE_PATH pointing to dependencies firebase and @firebase/rules-unit-testing.
// Requires a local Firestore emulator at 127.0.0.1:8088; never contacts production.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {doc,getDoc,setDoc,updateDoc,runTransaction,serverTimestamp,Timestamp}=require('firebase/firestore');
let env,seq=0;const nonce=()=>`n${++seq}`,clone=x=>JSON.parse(JSON.stringify(x));
const base={code:'TEST',schemaVersion:2,appVersion:'2.6',protocolVersion:26,lastClientVersion:'2.6',writeNonce:'first',name:'Table',phase:'active',joinLocked:false,hostId:'h',hostUid:'uh',coHostId:null,coHostUid:null,buyInCents:4000,revision:1,lastVerifiedRequestId:null,members:{uh:'h',ua:'a',ub:'b',uc:'c'},players:{}};
for(const id of ['h','a','b','c'])base.players[id]={id,name:id,authUid:'u'+id,buyins:[{id:id+'0',ts:1,kind:'initial',amountCents:4000,amount:40,approved:true,approvalMethod:'join'}],cashedOut:false,finalCents:null,finalAmount:null};
const db=id=>env.authenticatedContext('u'+id).firestore();const game=d=>doc(d,'poker_games_v2/TEST');const req=(d,id)=>doc(d,'poker_games_v2/TEST/requests/pending_'+id);const ctl=d=>doc(d,'poker_games_v2/TEST/host_control/current');
async function reset(cohost=false){await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const g=clone(base);if(cohost){g.coHostId='a';g.coHostUid='ua'}await setDoc(game(c.firestore()),g)})}
async function request(id,type='buyin',amountCents=4000){const d=db(id),g=(await getDoc(game(d))).data();return setDoc(req(d,id),{schemaVersion:2,clientVersion:'2.6',type,status:'pending',targetId:id,targetUid:'u'+id,requesterId:id,requesterUid:'u'+id,amountCents,amount:amountCents/100,approverId:id===g.hostId?null:g.hostId,approverUid:id===g.hostId?null:g.hostUid,ts:Date.now(),approvalMode:'tap',challengeId:nonce(),challengeExpiresAtMs:0})}
function meta(g){return {...g,revision:g.revision+1,writeNonce:nonce(),updatedAtMs:Date.now(),lastClientVersion:'2.6'}}
async function approve(actor,target,tamper=false,onlyRequest=false){const d=db(actor);return runTransaction(d,async tx=>{const gs=await tx.get(game(d)),rs=await tx.get(req(d,target)),g=gs.data(),r=rs.data();if(r.status!=='pending')throw Error('already resolved');let n=meta(g);n.players=clone(g.players);const p=n.players[target];if(r.type==='buyin'){p.buyins.push({id:nonce(),ts:Date.now(),kind:'rebuy',amountCents:r.amountCents,amount:r.amount,approved:true,approvedBy:actor,requestId:'pending_'+target,approvalMethod:'tap',challengeId:r.challengeId});if(tamper)p.buyins[0].amountCents=1;}else{p.cashedOut=true;p.finalCents=r.amountCents;p.finalAmount=r.amount;}n.lastVerifiedRequestId='pending_'+target;if(!onlyRequest)tx.set(game(d),n);tx.update(req(d,target),{status:'approved',decidedByUid:'u'+actor,decidedByPlayerId:actor,decidedAt:Date.now()});})}
function transfer(g,c){return {...meta(g),hostId:c.candidateId,hostUid:c.candidateUid,coHostId:null,coHostUid:null,hostEpoch:(g.hostEpoch||0)+1,lastHostTransfer:c.nonce}}
async function propose(actor,mode,candidate=actor){const d=db(actor);return runTransaction(d,async tx=>{const g=(await tx.get(game(d))).data();const c={mode,status:mode==='cohost'?'approved':'pending',candidateId:candidate,candidateUid:'u'+candidate,fromHostId:g.hostId,fromHostUid:g.hostUid,hostEpoch:g.hostEpoch||0,createdByUid:'u'+actor,createdAt:serverTimestamp(),nonce:nonce(),vote1Uid:null,vote2Uid:null};tx.set(ctl(d),c);if(mode==='cohost')tx.set(game(d),transfer(g,c));})}
async function vote(actor,forced=false){const d=db(actor);return runTransaction(d,async tx=>{const g=(await tx.get(game(d))).data(),c=(await tx.get(ctl(d))).data();let n={...c};if(c.mode==='transfer')n.status='approved';else if(!c.vote1Uid&&!forced)n.vote1Uid='u'+actor;else{n.vote2Uid='u'+actor;n.status='approved';}tx.set(ctl(d),n);if(n.status==='approved')tx.set(game(d),transfer(g,n));})}
(async()=>{
 env=await initializeTestEnvironment({projectId:'demo-poker',firestore:{host:'127.0.0.1',port:8088,rules:fs.readFileSync(path.join(__dirname,'../firestore.rules'),'utf8')}});
 await reset();await assertSucceeds(request('a'));await assertFails(request('a'));await assertFails(approve('a','a'));await assertFails(approve('b','a'));await assertFails(approve('h','a',true));await assertFails(approve('h','a',false,true));await assertSucceeds(approve('h','a'));await assert.rejects(approve('h','a'),/already resolved/);await assertSucceeds(request('a'));await assertSucceeds(approve('h','a'));
 assert.equal((await getDoc(game(db('h')))).data().players.a.buyins.length,3);
 console.log('PASS: one pending request, no self/peer approval, history immutable, atomic approval, exactly one append, reuse after resolution.');
 await request('h');await assertFails(approve('h','h'));await assertSucceeds(approve('b','h'));await request('h','cashout',7200);await assertSucceeds(approve('c','h'));
 console.log('PASS: any other member can approve host rebuy and cash-out.');
 await reset();await request('h');const concurrent=await Promise.allSettled([approve('a','h'),approve('b','h')]);assert.equal(concurrent.filter(x=>x.status==='fulfilled').length,1);assert.equal((await getDoc(game(db('a')))).data().players.h.buyins.length,2);
 console.log('PASS: racing approvals record exactly one rebuy.');
 await reset();await request('b');const before=(await getDoc(game(db('h')))).data(),pending=(await getDoc(req(db('h'),'b'))).data();await assertFails(propose('a','transfer','b'));await assertSucceeds(propose('h','transfer','a'));await assertFails(vote('b'));await assertSucceeds(vote('a'));let after=(await getDoc(game(db('a')))).data();assert.deepEqual(after.players,before.players);assert.deepEqual((await getDoc(req(db('a'),'b'))).data(),pending);assert.equal(after.hostId,'a');assert.equal(after.coHostId,null);await assertFails(approve('h','b'));await assertSucceeds(approve('a','b'));
 console.log('PASS: chosen player accepts handover; ledger and pending request preserved; old host loses approval rights.');
 await reset();await request('b');await assertSucceeds(propose('a','recovery'));await assertFails(vote('a'));await assertFails(vote('h'));await assertFails(vote('x'));await assertFails(vote('b',true));await assertSucceeds(vote('b'));assert.equal((await getDoc(game(db('a')))).data().hostId,'h');await assertFails(vote('b'));await assertSucceeds(vote('c'));after=(await getDoc(game(db('a')))).data();assert.equal(after.hostId,'a');assert.deepEqual(after.players,base.players);assert.equal((await getDoc(req(db('a'),'b'))).data().status,'pending');
 console.log('PASS: takeover requires two distinct other members, excludes candidate/old host, and preserves records.');
 await reset(true);await assertFails(propose('b','recovery'));await assertFails(propose('b','cohost'));await assertSucceeds(propose('a','cohost'));assert.equal((await getDoc(game(db('a')))).data().coHostId,null);
 await reset();await assertFails(updateDoc(game(db('h')),{hostEpoch:8,writeNonce:nonce()}));await propose('a','recovery');await env.withSecurityRulesDisabled(async c=>updateDoc(ctl(c.firestore()),{createdAt:Timestamp.fromMillis(Date.now()-601000)}));await assertFails(vote('b'));await assertSucceeds(propose('b','recovery'));
 console.log('PASS: assigned co-host only for direct takeover; expired proposals cannot be approved; host epoch cannot be forged.');

 await env.clearFirestore();await assertSucceeds(setDoc(game(db('h')),base));
 const joined=meta(clone(base));joined.members.ux='x';joined.players.x={...clone(base.players.a),id:'x',name:'x',authUid:'ux'};await assertSucceeds(setDoc(game(db('x')),joined));
 await assertSucceeds(updateDoc(game(db('h')),{coHostId:'a',coHostUid:'ua',writeNonce:nonce()}));let corrected=meta((await getDoc(game(db('a')))).data());corrected.players.h.buyins[0].voided=true;await assertSucceeds(setDoc(game(db('a')),corrected));
 corrected=meta(corrected);corrected.players.h.cashedOut=true;corrected.players.h.finalCents=100;corrected.players.h.finalAmount=1;await assertSucceeds(setDoc(game(db('a')),corrected));
 console.log('PASS: game creation, automatic initial buy-in on join, host settings and existing co-host ledger corrections remain authorized.');
 // Run the actual browser handlers against compat-style adapters backed by the emulator.
 const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');let raw=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(x=>x[1]).find(x=>x.includes('function PokerLedger()'));
 const helpers=raw.slice(raw.indexOf('function canApproveTableRequest'),raw.indexOf('function PokerLedger()'));
 const hc=vm.createContext({Date,Set,Object,Number,toCents:v=>Math.round(v*100),APP_VERSION:'2.6',uid:nonce});vm.runInContext(helpers,hc);
 let baseline=hc.newSavedRebuys(null,base);assert.equal(baseline.added.length,0);const changed=clone(base);changed.players.a.buyins.push({id:'new',kind:'rebuy',amountCents:4000});let update=hc.newSavedRebuys(baseline.seen,changed);assert.equal(update.added.length,1);assert.equal(update.added[0].targetId,'a');assert.equal(hc.newSavedRebuys(update.seen,changed).added.length,0);assert.equal(hc.newSavedRebuys(null,changed).added.length,0);
 console.log('PASS: saved rebuy detection emits once and suppresses historical/reconnect notifications.');

 function handler(name){const start=raw.search(new RegExp('  (?:async )?function '+name+'\\('));assert(start>=0);const rest=raw.slice(start);const end=rest.slice(3).search(/\n  (?:async )?function /);return end<0?rest:rest.slice(0,end+3);}
 async function actor(id){const d=db(id),g=(await getDoc(game(d))).data(),errors=[];const scope={console,Date,Set,Object,Number,JSON,APP_VERSION:'2.6',uid:nonce,toCents:v=>Math.round(v*100),fromCents:v=>v/100,role:{code:'TEST',playerId:id},game:g,pendingRequests:[],db:d,gamesCol:()=>d.collection('poker_games_v2'),ensureAuth:async()=>({uid:'u'+id}),boundPlayerId:(g,u)=>g.members[u],firebase:{firestore:{FieldValue:{serverTimestamp}}},setError:e=>errors.push(e),setShowTableControls:()=>{},setShowHostTransfer:()=>{}};const names=['createPendingRequest','approveTableRequest','proposeHost','decideHost'];const c=new Function(...Object.keys(scope),helpers+names.map(handler).join('\n')+';return {'+names.join(',')+'};')(...Object.values(scope));return {c,errors};}
 await reset();let a=await actor('a');assert.equal((await a.c.createPendingRequest('buyin','a',4000)).ok,true,JSON.stringify(a.errors));let h=await actor('h');assert.equal((await h.c.approveTableRequest('pending_a','buyin')).ok,true,JSON.stringify(h.errors));assert.equal((await getDoc(game(db('a')))).data().players.a.buyins.length,2);
 await h.c.proposeHost('transfer','a');assert.deepEqual(h.errors,[]);a=await actor('a');await a.c.decideHost('approve');assert.deepEqual(a.errors,[]);assert.equal((await getDoc(game(db('a')))).data().hostId,'a');
 await reset();a=await actor('a');await a.c.proposeHost('recovery','a');assert.deepEqual(a.errors,[]);for(const id of ['b','c']){const voter=await actor(id);await voter.c.decideHost('approve');assert.deepEqual(voter.errors,[]);}assert.equal((await getDoc(game(db('a')))).data().hostId,'a');

 await reset();a=await actor('a');await a.c.createPendingRequest('buyin','a',4000);h=await actor('h');assert.equal((await h.c.approveTableRequest('pending_a','buyin','stale-nonce')).ok,false);assert.equal((await getDoc(req(db('h'),'a'))).data().status,'pending');
 await reset();await env.withSecurityRulesDisabled(async c=>{const g=clone(base);delete g.members.ub;delete g.members.uc;delete g.players.b;delete g.players.c;await setDoc(game(c.firestore()),g)});a=await actor('a');await a.c.proposeHost('recovery','a');assert(a.errors[0].includes('two other players'));assert.equal((await getDoc(ctl(db('a')))).exists(),false);
 console.log('PASS: actual app transaction handlers create/approve rebuys, accept handover and complete two-vote recovery against Firestore rules.');
 await env.cleanup();
})().catch(async e=>{console.error(e);if(env)await env.cleanup();process.exitCode=1});
